version: '2'
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 4000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build: ${PROJECT_ROOT}/reschain-api/
    ports:
      - 6000:9000
    volumes:
      - ${PROJECT_ROOT}/reschain-api/:/app
      - /app/vendor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dontbreak@postgres/dontbreak
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dontbreak
      POSTGRES_DB: dontbreak
      POSTGRES_PASSWORD: 1111
    ports:
      - 3306:5432
    volumes:
      - ../PostgresData/data:/var/lib/postgresql/data
  redis:
    container_name: reschain-redis
    build: ./Redis/
    ports:
      - 6003:6379
    volumes:
      - ../RedisData/data:/data
    restart: always
    command: redis-server --appendonly yes
    depends_on:
      - api
  notification:
    build: ${PROJECT_ROOT}/reschain-go/
    ports:
     - 2001:80
    volumes:
      - ${PROJECT_ROOT}/reschain-go/:/usr/local/go/src/reschain-go
